version: '2'
services:
  config:
    build:
      context: ./config
    container_name: config-server
    restart: always
    ports:
      - 8081:8081
    volumes:
      - ./config:/usr/src/app
    environment:
      - GITHUB_TOKEN="YOU_SHALL_NOT_PASS-XD"
  registry:
    build:
      context: ./registry
    container_name: registry-server
    restart: always
    ports:
      - 8099:8099
    volumes:
      - ./registry:/usr/src/app
    links:
      - "config:config-server"
  admin:
    build:
      context: ./admin
    container_name: admin-server
    restart: always
    ports:
      - 8086:8086
    volumes:
      - ./admin:/usr/src/app
  gateway:
    build:
      context: ./gateway
    container_name: gateway-server
    restart: always
    ports:
      - 8080:8080
    links:
      - "config:config-server"
      - "registry:registry-server"
  products:
    build: ./primermicro
    container_name: product-server
    restart: always
    ports:
      - 8091:8091
    volumes:
      - ./primermicro:/usr/src/app
    links:
      - "config:config-server"
      - "registry:registry-server"
      - "admin:admin-server"
  customers:
    build: ./customer
    container_name: customer-server
    restart: always
    ports:
      - 8092:8092
    volumes:
      - ./customer:/usr/src/app
    links:
      - "config:config-server"
      - "registry:registry-server"
      - "admin:admin-server"
  shopping:
    build: ./shopping
    container_name: shopping-server
    restart: always
    ports:
      - 8093:8093
    volumes:
      - ./shopping:/usr/src/app
    links:
      - "config:config-server"
      - "registry:registry-server"
      - "admin:admin-server"
  grafana:
    container_name: grafana-server
    ports:
    - "3000:3000"
    volumes:
    - /var/lib/grafana
    links:
    - "prometheus:prometheus-server"
    image: grafana/grafana
  prometheus:
    container_name: prometheus-server
    ports:
    - 9090:9090
    volumes:
    - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
    - '--config.file=/etc/prometheus/prometheus.yml'
    image: prom/prometheus